package proyectofinal.vistas;
import java.awt.Font;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import proyectofinal.clases.Lector;
import proyectofinal.conexiones.*;

public class RegistrarLector extends javax.swing.JInternalFrame {


    public RegistrarLector() {
        initComponents();
        TextoEjemplo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtDni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtDomicilio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtTelefono = new javax.swing.JTextField();
        jBregistrar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Registrar lector");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/vistas/education_books_library_icon_149685.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Registro");

        jLabel2.setText("Nombre");

        jtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNombreFocusGained(evt);
            }
        });

        jLabel3.setText("DNI:");
        jLabel3.setToolTipText("");

        jtDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtDniFocusGained(evt);
            }
        });

        jLabel4.setText("Domicilio:");

        jtDomicilio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtDomicilioFocusGained(evt);
            }
        });

        jLabel5.setText("Telefono:");

        jtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtTelefonoFocusGained(evt);
            }
        });

        jBregistrar.setText("Registrar");
        jBregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtNombre)
                            .addComponent(jtDni)
                            .addComponent(jtDomicilio)
                            .addComponent(jtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jBregistrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBregistrar)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregistrarActionPerformed
        //Se utilizaba para detectar texto de ejemplo pero ya no es necesario
        /*  
        if(jtNombre.getForeground().equals(java.awt.Color.GRAY) ||
           jtDni.getForeground().equals(java.awt.Color.GRAY)||
           jtDomicilio.getForeground().equals(java.awt.Color.GRAY)||
           jtTelefono.getForeground().equals(java.awt.Color.GRAY)){//Si la condicion se cumple significa que este texto de ejemplo
            JOptionPane.showMessageDialog(this, "Por favor cargue todos los campos");
            return;
        }*/
        
        
        // Registrar Lector en la base de datos:
        String nombre = jtNombre.getText();
        Long dni=0L;
        String domicilio = jtDomicilio.getText();                       //Inicializamos las variables.
        Long telefono=0L;  
        
        for (char c : nombre.toCharArray()){
            if(Character.isDigit(c)){
                JOptionPane.showMessageDialog(this, "El nombre no puede contener numeros");
                jtNombre.setText("");
                return;
            }
        }
        
        
        try{
            if(!jtDni.getText().isEmpty() && !jtTelefono.getText().isEmpty() && !nombre.isEmpty() && !domicilio.isEmpty()){ //Comprobamos si algun campo clave del formulario esta vacio.
                if(jtDni.getText().length()==8){
                    dni = Long.parseLong(jtDni.getText());              //si todos los campos estan llenos intenta convertir el campo del dni y del telefono a tipo Long
                    telefono = Long.parseLong(jtTelefono.getText());
                }
                else{
                    JOptionPane.showMessageDialog(this,"ERROR\nLa longitud del dni debe ser de 8", "ERROR longitudinal", JOptionPane.ERROR_MESSAGE);    //Si algun campo clave esta vacio muestra un error.
                    return;//Retorna al inicio (Cancela la ejecucion del metodo)
                }
                
            }
            else{
                JOptionPane.showMessageDialog(this,"ERROR\nNo puede haber campos vacios", "ERROR de campos", JOptionPane.ERROR_MESSAGE);    //Si algun campo clave esta vacio muestra un error.
                return;//Retorna al inicio (Cancela la ejecucion del metodo)
            }
            
        }catch(NumberFormatException ex){//Error por si no puede convertir el String a Long
            JOptionPane.showMessageDialog(this,"ERROR\nEl numero de telefono y el documento deben ser de tipo numerico.", "ERROR al parsear", JOptionPane.ERROR_MESSAGE);  
            return;
        }
        //Si todo lo anterior funciono bien creamos un objeto de tipo Lector el cual luego sera subido a la base de datos.
        Lector lector = new Lector(nombre,dni,domicilio,telefono,true);
        LectorData lectordata= new LectorData();
        lectordata.RegistrarLector(lector);
        //JOptionPane.showMessageDialog(this, "El lector "+lector.getNombre()+" ha sido añadido exitosamente");
        jtDni.setText("");
        jtDomicilio.setText("");
        jtNombre.setText("");
        jtTelefono.setText("");
    }//GEN-LAST:event_jBregistrarActionPerformed

    private void jtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNombreFocusGained
        RestaurarTexto(jtNombre);
    }//GEN-LAST:event_jtNombreFocusGained

    private void jtDniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDniFocusGained
        RestaurarTexto(jtDni);
    }//GEN-LAST:event_jtDniFocusGained

    private void jtDomicilioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDomicilioFocusGained
        RestaurarTexto(jtDomicilio);
    }//GEN-LAST:event_jtDomicilioFocusGained

    private void jtTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtTelefonoFocusGained
        RestaurarTexto(jtTelefono);
    }//GEN-LAST:event_jtTelefonoFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBregistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTextField jtDomicilio;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtTelefono;
    // End of variables declaration//GEN-END:variables


    
    private void TextoEjemplo(){
    
        jtNombre.setForeground(java.awt.Color.GRAY);
        jtNombre.setFont(new Font("Tahoma",Font.ITALIC,16));
        jtNombre.setText("Raul...");
        
        jtDni.setForeground(java.awt.Color.GRAY);
        jtDni.setFont(new Font("Tahoma",Font.ITALIC,16));
        jtDni.setText("12345678");
        
        jtDomicilio.setForeground(java.awt.Color.GRAY);
        jtDomicilio.setFont(new Font("Tahoma",Font.ITALIC,16));
        jtDomicilio.setText("Ejemplo 123");
        
        jtTelefono.setForeground(java.awt.Color.GRAY);
        jtTelefono.setFont(new Font("Tahoma",Font.ITALIC,16));
        jtTelefono.setText("1122334455");
        
    }

    private void RestaurarTexto(JTextField text){
        System.out.println(Main.modoOscuro);
        if(text.getForeground().equals(java.awt.Color.GRAY))
            text.setText("");
        if(Main.modoOscuro){
            text.setForeground(java.awt.Color.WHITE);
            text.setFont(new Font("Tahoma",Font.PLAIN,16));
        }
        else{
            text.setForeground(java.awt.Color.BLACK);
            text.setFont(new Font("Tahoma",Font.PLAIN,16));
        }
    }
    
}
