    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal.vistas;
import com.formdev.flatlaf.util.ColorFunctions;
import com.toedter.calendar.JCalendar;
import java.awt.Color;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import proyectofinal.clases.Ejemplar;
import proyectofinal.clases.Lector;
import proyectofinal.clases.Prestamo;
import proyectofinal.conexiones.EjemplarData;
import proyectofinal.conexiones.LectorData;
import proyectofinal.conexiones.PrestamoData;
/**
 *
 * @author Chocobo
 */
public class RegistrarPrestamo extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrarPrestamos
     */
    public RegistrarPrestamo() {
        initComponents();
        CargarComboEjemplar();
        CargarComboLectores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jcbEjemplar = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jcbLector = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jrbEstado = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jdcInicio = new com.toedter.calendar.JDateChooser();
        jdcFin = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setTitle("Registrar prestamo");

        jLabel3.setText("Fecha fin:");

        jLabel5.setText("Lector:");

        jLabel6.setText("Estado:");

        jrbEstado.setText("¿Se encuentra activo?");

        jLabel4.setText("Ejemplar:");

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Registrar");

        jLabel2.setText("Fecha inicio:");

        jdcFin.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jrbEstado)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(102, 102, 102))
                                    .addComponent(jdcInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbLector, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbEjemplar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdcFin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jdcInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jdcFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jcbEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jcbLector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jrbEstado))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       
        if (jdcInicio.getDate()!=null && jdcFin.getDate()!=null){
            LocalDate fechaInicio=jdcInicio.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fechaFin=jdcFin.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            Ejemplar ej = (Ejemplar)jcbEjemplar.getSelectedItem();
            //Comprobamos si la cantidad de ejemplares es mayor que 0, si es asi podemos realizar el prestamo
            if(ej.getCantidad()>0){
                //Decrementar el ejemplar por el codigo.
                ej.setCantidad(ej.getCantidad()-1);
                //Obtenemos el lector del combobox
                Lector lect = (Lector) jcbLector.getSelectedItem();
                //Creamos un nuevo objeto de tipo prestamo y luego lo almacenamos en la base de datos.
                Prestamo prest = new Prestamo(fechaInicio, fechaFin, ej, lect, jrbEstado.isSelected());
                PrestamoData prestamodata = new PrestamoData();
                prestamodata.RegistrarPrestamo(prest);
                //decrementamos el ejemplar de la base de datos
                EjemplarData ejemplardata = new EjemplarData();
                ejemplardata.modificarEjemplar(ej);
            }
            else JOptionPane.showMessageDialog(this,"ERROR\nla cantidad de ejemplares tiene que ser mayor que 0", "ERROR cantidad de ejemplares invalida", JOptionPane.ERROR_MESSAGE);    //Si algun campo clave esta vacio muestra un error.

        }
        else JOptionPane.showMessageDialog(this,"ERROR\nLos campos de fechas no pueden ser vacios", "ERROR los campos no pueden ser vacios", JOptionPane.ERROR_MESSAGE);    //Si algun campo clave esta vacio muestra un error.
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<Ejemplar> jcbEjemplar;
    private javax.swing.JComboBox<Lector> jcbLector;
    private com.toedter.calendar.JDateChooser jdcFin;
    private com.toedter.calendar.JDateChooser jdcInicio;
    private javax.swing.JRadioButton jrbEstado;
    // End of variables declaration//GEN-END:variables


    private void CargarComboEjemplar(){
         EjemplarData ejemplarData = new EjemplarData();
         //ejemplarData.cargarEjemplaresEnComboBox(jComboBox1);
         for (Ejemplar ej:ejemplarData.buscarEjemplares()){
             jcbEjemplar.addItem(ej);
         }
    }
    
    private void CargarComboLectores(){
        LectorData lectorData = new LectorData();
        for (Lector lec: lectorData.buscarLectores()){
            jcbLector.addItem(lec);
        }
    }
    
}
